# Generated by Django 5.2.11 on 2026-02-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='Firebase Authentication UID', max_length=128, unique=True)),
                ('email', models.EmailField(help_text='User email from Firebase Auth', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', help_text='Authorization role', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the user was first created')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the request', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('user', models.ForeignKey(help_text='User who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.user')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_reques_user_id_ef8fb7_idx'), models.Index(fields=['status'], name='core_reques_status_27d5ad_idx'), models.Index(fields=['created_at'], name='core_reques_created_ee7b30_idx')],
            },
        ),
    ]
