# Generated by Django 4.2.28 on 2026-02-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned')], help_text='Type of action performed', max_length=20)),
                ('detail', models.TextField(blank=True, default='', help_text='Human-readable description of the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
            ],
            options={
                'verbose_name': 'Request Activity',
                'verbose_name_plural': 'Request Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.user'),
        ),
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Request priority level', max_length=6),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current workflow status', max_length=12),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to'], name='core_reques_assigne_e3e7f5_idx'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to='core.user'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='request',
            field=models.ForeignKey(help_text='The request this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.request'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['request', 'timestamp'], name='core_reques_request_3215c2_idx'),
        ),
    ]
