# Generated by Django 4.2.27 on 2026-01-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='Firebase Authentication UID', max_length=128, unique=True)),
                ('brand_name', models.CharField(help_text='Name of the brand/company', max_length=255)),
                ('email', models.EmailField(help_text='Brand contact email (from Firebase Auth)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when brand was first registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('website', 'Website Development'), ('uiux', 'UI/UX Design'), ('branding', 'Branding'), ('app', 'App Development'), ('canva', 'Canva Design')], help_text='Type of service requested', max_length=50)),
                ('requirements_text', models.TextField(help_text='Detailed requirements and description from the brand')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='submitted', help_text='Current status of the project', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when project was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('brand', models.ForeignKey(help_text='Brand that submitted this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.brand')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'status'], name='projects_pr_brand_i_93dbc3_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx')],
            },
        ),
    ]
